Repository pre-Q/preQ_Server, pull requests merged in 2023-09, with the labels that each got.

#75 [FEAT] application entity 설계
  src/main/java/kr/co/preq/domain/application/entity/Application.java
  src/main/java/kr/co/preq/domain/application/repository/ApplicationRepository.java
  src/main/java/kr/co/preq/domain/board/auth/controller/AuthController.java
  src/main/java/kr/co/preq/domain/board/auth/dto/AuthRequestDto.java
  src/main/java/kr/co/preq/domain/board/auth/dto/AuthResponseDto.java
  src/main/java/kr/co/preq/domain/board/auth/dto/LogoutRequestDto.java
  src/main/java/kr/co/preq/domain/board/auth/dto/TokenRequestDto.java
  src/main/java/kr/co/preq/domain/board/auth/service/AuthService.java
  src/main/java/kr/co/preq/domain/board/auth/service/GoogleAuthService.java
  src/main/java/kr/co/preq/domain/board/auth/service/KaKaoAuthService.java
  src/main/java/kr/co/preq/domain/board/controller/BoardController.java
  src/main/java/kr/co/preq/domain/comment/controller/CommentController.java
  src/main/java/kr/co/preq/domain/member/service/MemberService.java
  src/main/java/kr/co/preq/domain/preq/dto/PreqMapper.java
  src/main/java/kr/co/preq/domain/preq/entity/ApplicationChild.java
  src/main/java/kr/co/preq/domain/preq/entity/Preq.java
  src/main/java/kr/co/preq/domain/preq/repository/ApplicationChildRepository.java
  src/main/java/kr/co/preq/domain/preq/repository/CoverLetterRepository.java
  src/main/java/kr/co/preq/domain/preq/repository/PreqRepository.java
  src/main/java/kr/co/preq/domain/preq/service/OpenAIService.java
  src/main/java/kr/co/preq/domain/preq/service/PreqService.java
Labels: 🛠️ Server, ✨ Feature, 🍒 서경

#81 [Feat] application 추가 API
  src/main/java/kr/co/preq/domain/application/controller/ApplicationController.java
  src/main/java/kr/co/preq/domain/application/entity/Application.java
  src/main/java/kr/co/preq/domain/application/service/ApplicationService.java
  src/main/java/kr/co/preq/domain/auth/controller/AuthController.java
  src/main/java/kr/co/preq/domain/auth/dto/AuthRequestDto.java
  src/main/java/kr/co/preq/domain/auth/dto/AuthResponseDto.java
  src/main/java/kr/co/preq/domain/auth/dto/LogoutRequestDto.java
  src/main/java/kr/co/preq/domain/auth/dto/TokenRequestDto.java
  src/main/java/kr/co/preq/domain/auth/service/AuthService.java
  src/main/java/kr/co/preq/domain/auth/service/GoogleAuthService.java
  src/main/java/kr/co/preq/domain/auth/service/KaKaoAuthService.java
  src/main/java/kr/co/preq/domain/board/controller/BoardController.java
  src/main/java/kr/co/preq/domain/comment/controller/CommentController.java
  src/main/java/kr/co/preq/domain/member/service/MemberService.java
  src/main/java/kr/co/preq/domain/preq/service/PreqService.java
  src/main/java/kr/co/preq/global/common/util/response/SuccessCode.java
Labels: 🛠️ Server, ✨ Feature, 🍒 서경

#83 [fix] get question list 시 req application id 추가
  src/main/java/kr/co/preq/domain/preq/controller/PreqController.java
  src/main/java/kr/co/preq/domain/preq/entity/ApplicationChild.java
  src/main/java/kr/co/preq/domain/preq/repository/ApplicationChildRepository.java
  src/main/java/kr/co/preq/domain/preq/service/PreqService.java
Labels: 🛠️ Server, 🧱 Fix, 🫧 민지

#85 [Feat] 지원서 제목 수정 API
  src/main/java/kr/co/preq/domain/application/controller/ApplicationController.java
  src/main/java/kr/co/preq/domain/application/dto/ApplicationTitleUpdateRequestDto.java
  src/main/java/kr/co/preq/domain/application/entity/Application.java
  src/main/java/kr/co/preq/domain/application/service/ApplicationService.java
  src/main/java/kr/co/preq/global/common/util/response/SuccessCode.java
Labels: 🛠️ Server, ✨ Feature, 🫧 민지

#86 [Fix] router endpoint 수정
  src/main/java/kr/co/preq/domain/application/controller/ApplicationController.java
Labels: 🛠️ Server, 🧱 Fix, 🫧 민지

#87 [Fix] 지원서 메모 수정 API
  src/main/java/kr/co/preq/domain/application/controller/ApplicationController.java
  src/main/java/kr/co/preq/domain/application/dto/ApplicationMemoUpdateRequestDto.java
  src/main/java/kr/co/preq/domain/application/entity/Application.java
  src/main/java/kr/co/preq/domain/application/service/ApplicationService.java
  src/main/java/kr/co/preq/global/common/util/response/SuccessCode.java
Labels: 🛠️ Server, ✨ Feature, 🫧 민지

#88 [Feat] Application list 조회 API
  src/main/java/kr/co/preq/domain/application/controller/ApplicationController.java
  src/main/java/kr/co/preq/domain/application/dto/response/ApplicationListGetResponseDto.java
  src/main/java/kr/co/preq/domain/application/repository/ApplicationRepository.java
  src/main/java/kr/co/preq/domain/application/service/ApplicationService.java
  src/main/java/kr/co/preq/domain/preq/dto/CoverLetterResponseDto.java
  src/main/java/kr/co/preq/global/common/util/response/SuccessCode.java
Labels: 🛠️ Server, ✨ Feature, 🍒 서경

#94 [Fix] CICD 빌드 오류 해결
  src/main/java/kr/co/preq/domain/application/controller/ApplicationController.java
  src/main/java/kr/co/preq/domain/application/service/ApplicationService.java
  src/main/java/kr/co/preq/global/common/util/response/SuccessCode.java
Labels: 🛠️ Server, 🧱 Fix, 🍒 서경

#90 Feat/#89 bad request exception
  src/main/java/kr/co/preq/domain/application/controller/ApplicationController.java
  src/main/java/kr/co/preq/domain/application/service/ApplicationService.java
  src/main/java/kr/co/preq/global/common/util/exception/BadRequestException.java
  src/main/java/kr/co/preq/global/common/util/exception/RestExceptionHandler.java
Labels: 🛠️ Server, ✨ Feature, 🫧 민지

#100 [Fix] 리스트 조회 시 시간순 정렬 추가
  src/main/java/kr/co/preq/domain/application/repository/ApplicationRepository.java
  src/main/java/kr/co/preq/domain/application/service/ApplicationService.java
  src/main/java/kr/co/preq/domain/applicationChild/repository/ApplicationChildRepository.java
  src/main/java/kr/co/preq/domain/applicationChild/service/ApplicationChildService.java
Labels: 🛠️ Server, 🧱 Fix, 🫧 민지

#101 Fix/#99 delete old preqs
  src/main/java/kr/co/preq/domain/applicationChild/service/ApplicationChildService.java
  src/main/java/kr/co/preq/domain/preq/repository/PreqRepository.java
  src/main/java/kr/co/preq/domain/preq/service/PreqService.java
Labels: 🛠️ Server, 🧱 Fix, 🫧 민지

#104 [Add] add answer at get application child response dto
  src/main/java/kr/co/preq/domain/applicationChild/dto/response/ApplicationChildListResponseDto.java
  src/main/java/kr/co/preq/domain/applicationChild/dto/response/ApplicationChildMapper.java
Labels: enhancement, 🛠️ Server, 🫧 민지

#103 [Feat] 지원서 개별 조회 API
  src/main/java/kr/co/preq/domain/application/controller/ApplicationController.java
  src/main/java/kr/co/preq/domain/application/dto/response/ApplicationGetResponseDto.java
  src/main/java/kr/co/preq/domain/application/entity/Application.java
  src/main/java/kr/co/preq/domain/application/service/ApplicationService.java
  src/main/java/kr/co/preq/domain/applicationChild/dto/response/ApplicationChildMapper.java
  src/main/java/kr/co/preq/domain/applicationChild/dto/response/ApplicationChildResponseDto.java
  src/main/java/kr/co/preq/domain/applicationChild/repository/ApplicationChildRepository.java
  src/main/java/kr/co/preq/domain/preq/service/PreqService.java
  src/main/java/kr/co/preq/global/common/util/response/SuccessCode.java
Labels: 🛠️ Server, ✨ Feature, 🍒 서경

#108 Feat/#106 delete application child
  src/main/java/kr/co/preq/domain/application/controller/ApplicationController.java
  src/main/java/kr/co/preq/domain/application/repository/ApplicationRepository.java
  src/main/java/kr/co/preq/domain/application/service/ApplicationService.java
  src/main/java/kr/co/preq/domain/applicationChild/controller/ApplicationChildController.java
  src/main/java/kr/co/preq/domain/applicationChild/repository/ApplicationChildRepository.java
  src/main/java/kr/co/preq/domain/applicationChild/service/ApplicationChildService.java
  src/main/java/kr/co/preq/global/common/entity/BaseEntity.java
  src/main/java/kr/co/preq/global/common/util/response/SuccessCode.java
Labels: 🛠️ Server, ✨ Feature, 🫧 민지

#112 Add/#111 tail questions
  src/main/java/kr/co/preq/domain/applicationChild/dto/request/ApplicationChildRequestDto.java
  src/main/java/kr/co/preq/domain/applicationChild/entity/ApplicationChild.java
  src/main/java/kr/co/preq/domain/applicationChild/repository/ApplicationChildRepository.java
  src/main/java/kr/co/preq/domain/applicationChild/service/ApplicationChildService.java
  src/main/java/kr/co/preq/domain/preq/dto/SessionDto.java
  src/main/java/kr/co/preq/domain/preq/dto/request/OpenAIRequestDto.java
  src/main/java/kr/co/preq/domain/preq/service/OpenAIService.java
  src/main/java/kr/co/preq/domain/preq/service/PreqService.java
Labels: 🛠️ Server, ✨ Feature, 🫧 민지

#114 [Fix] recursive query param 오류 수정
  src/main/java/kr/co/preq/domain/applicationChild/repository/ApplicationChildRepository.java
Labels: 🛠️ Server, 🧱 Fix, 🫧 민지

#116 Fix/#115 chatgpt response after processing
  src/main/java/kr/co/preq/domain/preq/service/OpenAIService.java
  src/main/java/kr/co/preq/domain/preq/service/PreqService.java
Labels: 🛠️ Server, 🧱 Fix, 🫧 민지

#118 [Fix] 댓글 리스트 조회 시 정렬 추가
  src/main/java/kr/co/preq/domain/board/service/BoardService.java
  src/main/java/kr/co/preq/domain/comment/repository/CommentRepository.java
Labels: 🛠️ Server, 🧱 Fix, 🫧 민지
