Repository pre-Q/preQ_Server, pull requests merged in 2023-06, with the labels that each got.

#56 [Feat] 게시글 삭제 API
  src/main/java/kr/co/preq/domain/board/controller/BoardController.java
  src/main/java/kr/co/preq/domain/board/service/BoardService.java
  src/main/java/kr/co/preq/global/common/util/response/SuccessCode.java
Labels: 🛠️ Server, ✨ Feature, 🍒 서경

#57 [Feat] 댓글 삭제 API
  src/main/java/kr/co/preq/domain/board/service/BoardService.java
  src/main/java/kr/co/preq/domain/comment/controller/CommentController.java
  src/main/java/kr/co/preq/domain/comment/service/CommentService.java
  src/main/java/kr/co/preq/global/common/util/response/ErrorCode.java
Labels: 🛠️ Server, ✨ Feature, 🍒 서경

#60 [Add] cors 에러 방지
  src/main/java/kr/co/preq/global/config/WebMvcConfig.java
Labels: 🛠️ Server, ✨ Feature, 🍒 서경

#62 [Fix] flask url 수정
  src/main/java/kr/co/preq/domain/preq/service/PreqService.java
Labels: enhancement, 🛠️ Server, 🫧 민지

#63 [Chore] cors 수정
  src/main/java/kr/co/preq/global/config/WebMvcConfig.java
Labels: 🛠️ Server, ✨ Feature, 🍒 서경

#67 [Feat] keyword entity 구현
  src/main/java/kr/co/preq/domain/preq/entity/Keyword.java
Labels: enhancement, 🛠️ Server, 🫧 민지

#68 [Feat] 게시판 검색 API
  src/main/java/kr/co/preq/domain/board/controller/BoardController.java
  src/main/java/kr/co/preq/domain/board/repository/BoardRepository.java
  src/main/java/kr/co/preq/domain/board/service/BoardService.java
  src/main/java/kr/co/preq/global/common/util/response/ErrorCode.java
  src/main/java/kr/co/preq/global/common/util/response/SuccessCode.java
Labels: 🛠️ Server, ✨ Feature, 🍒 서경

#71 [Feat] 프로필 조회 API 구현
  src/main/java/kr/co/preq/domain/member/controller/MemberController.java
  src/main/java/kr/co/preq/domain/member/dto/MemberResponseDto.java
  src/main/java/kr/co/preq/domain/member/service/MemberService.java
Labels: 🛠️ Server, ✨ Feature, 🫧 민지

#73 [Feat] 회원 탈퇴 API 구현
  src/main/java/kr/co/preq/domain/member/controller/MemberController.java
  src/main/java/kr/co/preq/domain/member/entity/Member.java
  src/main/java/kr/co/preq/domain/member/service/MemberService.java
  src/main/java/kr/co/preq/global/common/entity/BaseEntity.java
  src/main/java/kr/co/preq/global/common/util/response/ErrorCode.java
  src/main/java/kr/co/preq/global/common/util/response/SuccessCode.java
Labels: 🛠️ Server, ✨ Feature, 🫧 민지
