Repository pre-Q/preQ_Server, pull requests merged in 2023-05, with the labels that each got.

#11 [Add] Spring Security & JWT
  .gitignore
  build.gradle
  src/main/java/kr/co/preq/global/common/util/SecurityUtil.java
  src/main/java/kr/co/preq/global/common/util/jwt/JwtAccessDeniedHandler.java
  src/main/java/kr/co/preq/global/common/util/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/kr/co/preq/global/common/util/jwt/JwtFilter.java
  src/main/java/kr/co/preq/global/common/util/jwt/TokenDto.java
  src/main/java/kr/co/preq/global/common/util/jwt/TokenInfo.java
  src/main/java/kr/co/preq/global/common/util/jwt/TokenProvider.java
  src/main/java/kr/co/preq/global/config/JwtSecurityConfig.java
  src/main/java/kr/co/preq/global/config/SecurityConfig.java
Labels: 🛠️ Server, 🫧 민지

#15 [Feat] 로그인 API 구현
  src/main/java/kr/co/preq/domain/auth/controller/AuthController.java
  src/main/java/kr/co/preq/domain/auth/dto/AuthRequestDto.java
  src/main/java/kr/co/preq/domain/auth/dto/AuthResponseDto.java
  src/main/java/kr/co/preq/domain/auth/service/AuthService.java
  src/main/java/kr/co/preq/domain/auth/service/GoogleAuthService.java
  src/main/java/kr/co/preq/domain/auth/service/KaKaoAuthService.java
  src/main/java/kr/co/preq/domain/member/dto/MemberRequestDto.java
  src/main/java/kr/co/preq/domain/member/service/AuthService.java
  src/main/java/kr/co/preq/global/common/entity/BaseEntity.java
  src/main/java/kr/co/preq/global/common/util/jwt/TokenProvider.java
  src/main/java/kr/co/preq/global/config/SecurityConfig.java
Labels: enhancement, 🛠️ Server, 🫧 민지

#16 [Fix] getAuthentication 오류 수정
  src/main/java/kr/co/preq/domain/preq/service/PreqService.java
  src/main/java/kr/co/preq/global/common/entity/BaseEntity.java
  src/main/java/kr/co/preq/global/common/util/jwt/TokenProvider.java
Labels: 🛠️ Server, 🧱 Fix, 🫧 민지

#23 [Chore] 자기소개서 입력 API
  src/main/java/kr/co/preq/domain/preq/controller/PreqController.java
  src/main/java/kr/co/preq/domain/preq/dto/CoverLetterResponseDto.java
  src/main/java/kr/co/preq/domain/preq/entity/CoverLetter.java
  src/main/java/kr/co/preq/domain/preq/service/PreqService.java
Labels: 🛠️ Server, ✨ Feature, 🍒 서경

#25 [Add] 예상 면접 질문 조회
  src/main/java/kr/co/preq/domain/preq/controller/PreqController.java
  src/main/java/kr/co/preq/domain/preq/dto/PreqResponseDto.java
  src/main/java/kr/co/preq/domain/preq/repository/CoverLetterRepository.java
  src/main/java/kr/co/preq/domain/preq/service/ChatGPT.py
  src/main/java/kr/co/preq/domain/preq/service/PreqService.java
  src/main/java/kr/co/preq/global/common/util/response/SuccessCode.java
Labels: 🛠️ Server, ✨ Feature, 🍒 서경

#26 [Feat] 예상 면접 질문 조회 API + OpenAI 연결
  .gitignore
  build.gradle
  src/main/java/kr/co/preq/domain/preq/controller/PreqController.java
  src/main/java/kr/co/preq/domain/preq/dto/Choice.java
  src/main/java/kr/co/preq/domain/preq/dto/CoverLetterResponseDto.java
  src/main/java/kr/co/preq/domain/preq/dto/Message.java
  src/main/java/kr/co/preq/domain/preq/dto/OpenAIRequestDto.java
  src/main/java/kr/co/preq/domain/preq/dto/OpenAIResponseDto.java
  src/main/java/kr/co/preq/domain/preq/dto/PreqMapper.java
  src/main/java/kr/co/preq/domain/preq/dto/PreqResponseDto.java
  src/main/java/kr/co/preq/domain/preq/entity/CoverLetter.java
  src/main/java/kr/co/preq/domain/preq/entity/Preq.java
  src/main/java/kr/co/preq/domain/preq/repository/PreqRepository.java
  src/main/java/kr/co/preq/domain/preq/service/ChatGPT.py
  src/main/java/kr/co/preq/domain/preq/service/PreqService.java
  src/main/java/kr/co/preq/global/common/util/response/ErrorCode.java
  src/main/java/kr/co/preq/global/common/util/response/SuccessCode.java
Labels: 🛠️ Server, ✨ Feature, 🍒 서경

#29 [Feat] 지원서 리스트 조회 API 구현
  src/main/java/kr/co/preq/domain/preq/controller/PreqController.java
  src/main/java/kr/co/preq/domain/preq/dto/CoverLetterMapper.java
  src/main/java/kr/co/preq/domain/preq/dto/CoverLetterResponseDto.java
  src/main/java/kr/co/preq/domain/preq/repository/CoverLetterRepository.java
  src/main/java/kr/co/preq/domain/preq/service/PreqService.java
Labels: 🛠️ Server, ✨ Feature, 🫧 민지

#35 [Feat] #17 게시글 수정 API 구현
  src/main/java/kr/co/preq/domain/board/controller/BoardController.java
  src/main/java/kr/co/preq/domain/board/dto/BoardRequestDto.java
  src/main/java/kr/co/preq/domain/board/entity/Board.java
  src/main/java/kr/co/preq/domain/board/service/BoardService.java
  src/main/java/kr/co/preq/global/common/util/response/ApiResponse.java
  src/main/java/kr/co/preq/global/common/util/response/ErrorCode.java
  src/main/java/kr/co/preq/global/common/util/response/SuccessCode.java
Labels: 🛠️ Server, ✨ Feature, 🍒 서경

#38 [fix] 토큰만료시간 수정
  src/main/java/kr/co/preq/global/common/util/jwt/TokenInfo.java
Labels: enhancement, 🛠️ Server, 🧱 Fix, 🫧 민지

#39 [Feat] 게시판 전체 조회
  src/main/java/kr/co/preq/domain/board/controller/BoardController.java
  src/main/java/kr/co/preq/domain/board/dto/BoardCreateResponseDto.java
  src/main/java/kr/co/preq/domain/board/dto/BoardGetResponseDto.java
  src/main/java/kr/co/preq/domain/board/entity/Board.java
  src/main/java/kr/co/preq/domain/board/service/BoardService.java
  src/main/java/kr/co/preq/global/common/util/response/ErrorCode.java
  src/main/java/kr/co/preq/global/common/util/response/SuccessCode.java
Labels: ✨ Feature, 🍒 서경

#40 [add] redis 설정
  src/main/java/kr/co/preq/global/common/util/RedisUtil.java
  src/main/java/kr/co/preq/global/config/RedisConfig.java
Labels: enhancement, 🛠️ Server, 🫧 민지

#42 [feat] refresh API 구현
  .gitignore
  src/main/java/kr/co/preq/domain/auth/controller/AuthController.java
  src/main/java/kr/co/preq/domain/auth/dto/TokenRequestDto.java
  src/main/java/kr/co/preq/domain/auth/service/AuthService.java
  src/main/java/kr/co/preq/domain/member/entity/Member.java
  src/main/java/kr/co/preq/global/common/util/jwt/CustomUserDetailsService.java
  src/main/java/kr/co/preq/global/common/util/jwt/TokenProvider.java
  src/main/java/kr/co/preq/global/config/SecurityConfig.java
Labels: 🛠️ Server, ✨ Feature, 🫧 민지

#46 [Rename] get -> getAll
  src/main/java/kr/co/preq/domain/board/controller/BoardController.java
  src/main/java/kr/co/preq/domain/board/dto/BoardGetAllResponseDto.java
  src/main/java/kr/co/preq/domain/board/dto/BoardGetResponseDto.java
  src/main/java/kr/co/preq/domain/board/service/BoardService.java
Labels: ✨ Feature, 🍒 서경

#48 [Feat] 댓글 작성 API
  src/main/java/kr/co/preq/domain/board/dto/BoardGetResponseDto.java
  src/main/java/kr/co/preq/domain/comment/controller/CommentController.java
  src/main/java/kr/co/preq/domain/comment/dto/CommentCreateResponseDto.java
  src/main/java/kr/co/preq/domain/comment/dto/CommentRequestDto.java
  src/main/java/kr/co/preq/domain/comment/repository/CommentRepository.java
  src/main/java/kr/co/preq/domain/comment/service/CommentService.java
  src/main/java/kr/co/preq/global/common/util/response/ErrorCode.java
Labels: 🛠️ Server, ✨ Feature, 🍒 서경

#50 [Feat] 글 상세조회 API
  src/main/java/kr/co/preq/domain/board/controller/BoardController.java
  src/main/java/kr/co/preq/domain/board/dto/BoardGetResponseDto.java
  src/main/java/kr/co/preq/domain/board/entity/Board.java
  src/main/java/kr/co/preq/domain/board/service/BoardService.java
  src/main/java/kr/co/preq/domain/comment/dto/CommentResponseDto.java
  src/main/java/kr/co/preq/domain/comment/repository/CommentRepository.java
  src/main/java/kr/co/preq/global/common/util/response/SuccessCode.java
Labels: 🛠️ Server, ✨ Feature, 🍒 서경

#55 [add] 키워드 추출 기능 추가
  src/main/java/kr/co/preq/domain/preq/dto/ApplicationRequestDto.java
  src/main/java/kr/co/preq/domain/preq/dto/ApplicationResponseDto.java
  src/main/java/kr/co/preq/domain/preq/dto/CoverLetterAndPreqResponseDto.java
  src/main/java/kr/co/preq/domain/preq/dto/PreqMapper.java
  src/main/java/kr/co/preq/domain/preq/service/PreqService.java
Labels: enhancement, 🛠️ Server, 🫧 민지
